-- 1. ENUMS (Strict types for your dropdowns)
create type user_role as enum ('FEDEX_ADMIN', 'DCA_AGENT');
create type case_status_enum as enum ('OPEN', 'IN_PROGRESS', 'PAID', 'DISPUTE');
create type priority_level_enum as enum ('HIGH', 'MEDIUM', 'LOW');

-- 2. PROFILES (The Users)
-- This links Supabase Auth to your Role logic
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  role user_role default 'DCA_AGENT',
  organization_id text, -- Matches 'dca_id' in your CSV (e.g., 'DCA_A')
  full_name text,
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);

create table public.cases (
  -- 1. Identifiers
  case_id text primary key, 
  customer_id text, 
  customer_name text,
  
  -- 2. The Debt (Context)
  invoice_amount numeric,
  amount_recovered numeric default 0,
  days_overdue int,
  case_status case_status_enum default 'OPEN',
  
  -- 3. The AI & Risk (Your ML Model Outputs)
  risk_score float,          -- 0.0 to 100.0
  priority_level priority_level_enum, -- HIGH/MED/LOW
  predicted_recovery_date date, -- AI prediction (optional)
  
  -- 4. The Allocation (The Bridge)
  dca_id text, -- MATCHES 'organization_id' in profiles (e.g. 'DCA_A')
  dca_performance_score int, -- From CSV
  assigned_date timestamp,
  
  -- 5. Audit & Operations (Flags)
  sla_breach_count int default 0,
  escalation_flag boolean default false,
  escalation_reason text,
  last_action_date timestamp,
  next_followup_date timestamp
);

-- Enable RLS
alter table public.cases enable row level security;

create table public.case_actions (
  id bigint generated by default as identity primary key,
  case_id text references public.cases(case_id), -- Links to Master Table
  performed_by uuid references auth.users(id),
  action_type text, -- 'CALL', 'EMAIL', 'PROMISE_TO_PAY'
  sentiment_score float, -- For your "Compliance AI" demo
  note text,
  created_at timestamp default now()
);

-- A. FedEx Admins see EVERYTHING
create policy "FedEx Admin View All"
on public.cases for select
using (
  (select role from public.profiles where id = auth.uid()) = 'FEDEX_ADMIN'
);

-- B. DCAs only see THEIR cases
create policy "DCA View Assigned Only"
on public.cases for select
using (
  dca_id = (select organization_id from public.profiles where id = auth.uid())
);

-- C. Everyone can Insert Logs (Audit Trail)
create policy "Log Actions"
on public.case_actions for insert
with check (auth.uid() = performed_by);