-- Final Complete Database Schema for FedEx Debt Collection Platform
-- This migration creates the complete database structure with proper roles, cases, and audit trail

-- Drop existing objects if they exist to rebuild cleanly
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can view cases" ON public.cases;
DROP POLICY IF EXISTS "Authenticated users can insert cases" ON public.cases;
DROP POLICY IF EXISTS "Authenticated users can update cases" ON public.cases;
DROP TABLE IF EXISTS public.case_actions;
DROP TABLE IF EXISTS public.cases;
DROP TABLE IF EXISTS public.profiles;
DROP TYPE IF EXISTS priority_level_enum;
DROP TYPE IF EXISTS case_status_enum;
DROP TYPE IF EXISTS user_role;

-- 1. ENUMS (Strict types for your dropdowns)
CREATE TYPE user_role AS ENUM ('FEDEX_ADMIN', 'DCA_MANAGER', 'DCA_AGENT');
CREATE TYPE case_status_enum AS ENUM ('OPEN', 'IN_PROGRESS', 'PAID', 'DISPUTE');
CREATE TYPE priority_level_enum AS ENUM ('HIGH', 'MEDIUM', 'LOW');

-- 2. PROFILES (The Users)
-- This links Supabase Auth to your Role logic
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  email TEXT,
  role user_role DEFAULT 'DCA_AGENT',
  organization_id TEXT, -- Matches 'dca_id' in your CSV (e.g., 'DCA_A')
  full_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);

-- 3. CASES (The Main Data)
CREATE TABLE public.cases (
  -- 1. Identifiers
  case_id TEXT PRIMARY KEY, -- Use 'CASE_1', 'CASE_2' from CSV
  customer_id TEXT, 
  customer_name TEXT,
  
  -- 2. The Debt (Context)
  invoice_amount NUMERIC,
  amount_recovered NUMERIC DEFAULT 0,
  days_overdue INT,
  case_status case_status_enum DEFAULT 'OPEN',
  
  -- 3. Customer Profile (For ML Model)
  customer_type TEXT, -- SME, Enterprise, Individual
  credit_score INT,
  past_recovery_rate NUMERIC, -- 0.0 to 1.0
  dispute_history INT, -- Number of past disputes
  
  -- 4. The AI & Risk (Your ML Model Outputs)
  risk_score FLOAT,          -- 0.0 to 100.0
  priority_level priority_level_enum, -- HIGH/MED/LOW
  predicted_recovery_date DATE, -- AI prediction (optional, filled by ML model)
  
  -- 5. The Allocation (The Bridge)
  dca_id TEXT, -- MATCHES 'organization_id' in profiles (e.g. 'DCA_A')
  dca_performance_score INT, -- From CSV
  assigned_date TIMESTAMP,
  
  -- 6. Case Lifecycle & Recovery Data
  case_created_date DATE,
  payment_date DATE,
  case_closed_date DATE,
  recovered BOOLEAN DEFAULT false, -- Whether payment was recovered
  
  -- 7. Action Analytics (For ML Model)
  action_count INT DEFAULT 0,
  last_action_type TEXT, -- Last action taken on case
  
  -- 8. Audit & Operations (Flags)
  sla_breach_count INT DEFAULT 0,
  escalation_flag BOOLEAN DEFAULT false,
  escalation_reason TEXT,
  last_action_date TIMESTAMP,
  next_followup_date TIMESTAMP,
  
  -- 9. Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS for cases
ALTER TABLE public.cases ENABLE ROW LEVEL SECURITY;

-- 4. CASE ACTIONS (Audit Trail)
CREATE TABLE public.case_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id TEXT REFERENCES public.cases(case_id), -- Links to Master Table
  performed_by UUID REFERENCES auth.users(id),
  action_type TEXT, -- 'CALL', 'EMAIL', 'PROMISE_TO_PAY'
  sentiment_score FLOAT, -- For your "Compliance AI" demo
  note TEXT,
  created_at TIMESTAMP DEFAULT now()
);

-- Enable RLS for case actions
ALTER TABLE public.case_actions ENABLE ROW LEVEL SECURITY;

-- 5. AGENT CASE ASSIGNMENTS (Personal case assignment for agents)
CREATE TABLE public.agent_case_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id UUID REFERENCES auth.users(id),
  case_id TEXT REFERENCES public.cases(case_id),
  assigned_date TIMESTAMP DEFAULT now(),
  UNIQUE(agent_id, case_id)
);

-- Enable RLS for agent assignments
ALTER TABLE public.agent_case_assignments ENABLE ROW LEVEL SECURITY;

-- 6. RLS POLICIES

-- A. FedEx Admins see EVERYTHING
CREATE POLICY "FedEx Admin View All"
ON public.cases FOR SELECT
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'FEDEX_ADMIN'
);

-- B. DCA MANAGERS can see their organization cases
CREATE POLICY "DCA Manager View Organization Cases"
ON public.cases FOR SELECT
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'DCA_MANAGER'
  AND dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- C. DCA AGENTS only see THEIR personally assigned cases
CREATE POLICY "DCA Agent View Assigned Only"
ON public.cases FOR SELECT
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'DCA_AGENT'
  AND case_id IN (
    SELECT case_id FROM public.agent_case_assignments WHERE agent_id = auth.uid()
  )
);

-- D. FedEx Admins can insert/update all cases
CREATE POLICY "FedEx Admin Modify All"
ON public.cases FOR ALL
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'FEDEX_ADMIN'
);

-- E. DCA Managers can insert/update cases in their organization
CREATE POLICY "DCA Manager Modify Organization"
ON public.cases FOR ALL
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'DCA_MANAGER'
  AND dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- F. DCA Agents can update their assigned cases
CREATE POLICY "DCA Agent Update Assigned"
ON public.cases FOR UPDATE
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'DCA_AGENT'
  AND dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- G. Everyone can Insert Logs (Audit Trail)
CREATE POLICY "Log Actions"
ON public.case_actions FOR INSERT
WITH CHECK (auth.uid() = performed_by);

-- H. Users can view logs for cases they have access to
CREATE POLICY "View Case Actions"
ON public.case_actions FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.cases c
    WHERE c.case_id = case_actions.case_id
    AND (
      (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'FEDEX_ADMIN'
      OR
      c.dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
    )
  )
);

-- I. Agent Assignment Policies
-- Agents can view their own assignments
CREATE POLICY "Agents View Own Assignments"
ON public.agent_case_assignments FOR SELECT
USING (agent_id = auth.uid());

-- Managers and Admins can view all assignments in their organization
CREATE POLICY "Managers View Organization Assignments"
ON public.agent_case_assignments FOR SELECT
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('FEDEX_ADMIN', 'DCA_MANAGER')
);

-- Only Managers can assign cases to agents in their organization
CREATE POLICY "Managers Assign Cases"
ON public.agent_case_assignments FOR INSERT
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('FEDEX_ADMIN', 'DCA_MANAGER')
);

-- 7. TRIGGER FUNCTION FOR USER SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    org_type TEXT := new.raw_user_meta_data->>'organization_type';
    selected_dca TEXT := new.raw_user_meta_data->>'selected_dca';
BEGIN
    INSERT INTO public.profiles (id, email, role, organization_id, full_name)
    VALUES (
        new.id,
        new.email,
        CASE 
            WHEN org_type = 'FedEx Administrator' THEN 'FEDEX_ADMIN'::user_role
            WHEN org_type = 'Agency Manager' THEN 'DCA_MANAGER'::user_role
            WHEN org_type = 'Agency Agent' THEN 'DCA_AGENT'::user_role
            ELSE 'DCA_AGENT'::user_role
        END,
        CASE 
            WHEN org_type = 'FedEx Administrator' THEN 'FEDEX_HQ'
            WHEN org_type = 'Agency Manager' AND selected_dca IS NOT NULL THEN selected_dca
            WHEN org_type = 'Agency Agent' THEN 'DCA_A'  -- Default agents to DCA_A
            ELSE 'DCA_C' -- Default for empty/unknown cases
        END,
        COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1))
    );
    RETURN new;
END;
$$;

-- 7. TRIGGER TO CREATE PROFILE ON USER SIGNUP
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 8. CREATE INDEXES FOR BETTER PERFORMANCE
CREATE INDEX idx_cases_case_id ON public.cases(case_id);
CREATE INDEX idx_cases_status ON public.cases(case_status);
CREATE INDEX idx_cases_priority ON public.cases(priority_level);
CREATE INDEX idx_cases_dca_id ON public.cases(dca_id);
CREATE INDEX idx_cases_customer ON public.cases(customer_name);
CREATE INDEX idx_cases_assigned_date ON public.cases(assigned_date);
CREATE INDEX idx_case_actions_case_id ON public.case_actions(case_id);
CREATE INDEX idx_case_actions_performed_by ON public.case_actions(performed_by);

-- 9. UPDATED AT TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 10. APPLY UPDATED AT TRIGGER TO CASES
CREATE TRIGGER handle_cases_updated_at BEFORE UPDATE ON public.cases
    FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();
