-- Migration: Add Finance & Settlement Tables for DCA Manager
-- Date: 2026-02-06

-- 1. Create settlements/remittance batches table
CREATE TABLE IF NOT EXISTS public.settlement_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id TEXT UNIQUE NOT NULL, -- e.g., BATCH-101
  dca_id TEXT NOT NULL, -- Links to DCA organization
  created_by UUID REFERENCES auth.users(id),
  
  -- Financial details
  total_amount NUMERIC NOT NULL DEFAULT 0,
  case_count INT NOT NULL DEFAULT 0,
  commission_rate NUMERIC DEFAULT 0.10, -- 10% default
  commission_amount NUMERIC DEFAULT 0,
  
  -- Bank transfer details
  utr_number TEXT, -- Bank transaction reference
  bank_name TEXT,
  proof_url TEXT, -- Uploaded screenshot/document
  
  -- Status tracking
  status TEXT DEFAULT 'PENDING', -- PENDING, SUBMITTED, VERIFIED, REJECTED
  fedex_verified_at TIMESTAMP,
  fedex_verified_by UUID,
  commission_status TEXT DEFAULT 'PENDING', -- PENDING, APPROVED, PAID
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  submitted_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. Create case payments table (tracks individual payments from customers)
CREATE TABLE IF NOT EXISTS public.case_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id TEXT REFERENCES public.cases(case_id),
  
  -- Payment details
  payment_amount NUMERIC NOT NULL,
  payment_date DATE NOT NULL,
  payment_method TEXT, -- CASH, CHEQUE, BANK_TRANSFER, UPI, CARD
  reference_number TEXT, -- Cheque number or transaction ID
  
  -- Recording details
  recorded_by UUID REFERENCES auth.users(id), -- The agent who logged this
  dca_id TEXT NOT NULL,
  
  -- Settlement linking
  settlement_batch_id BIGINT REFERENCES public.settlement_batches(id),
  is_settled BOOLEAN DEFAULT false,
  settled_at TIMESTAMP,
  
  -- Status
  status TEXT DEFAULT 'UNSETTLED', -- UNSETTLED, BATCHED, SETTLED, DISPUTED
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Enable RLS
ALTER TABLE public.settlement_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.case_payments ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies for settlement_batches
-- FedEx Admin can see all
CREATE POLICY "FedEx Admin View All Settlements"
ON public.settlement_batches FOR SELECT
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'FEDEX_ADMIN'
);

-- DCA Manager can see their organization's settlements
CREATE POLICY "DCA Manager View Organization Settlements"
ON public.settlement_batches FOR SELECT
USING (
  dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- DCA Manager can create settlements for their organization
CREATE POLICY "DCA Manager Create Settlements"
ON public.settlement_batches FOR INSERT
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'DCA_MANAGER'
  AND dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- DCA Manager can update their settlements
CREATE POLICY "DCA Manager Update Settlements"
ON public.settlement_batches FOR UPDATE
USING (
  dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- FedEx Admin can update all settlements (for verification)
CREATE POLICY "FedEx Admin Update All Settlements"
ON public.settlement_batches FOR ALL
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'FEDEX_ADMIN'
);

-- 5. RLS Policies for case_payments
-- FedEx Admin can see all
CREATE POLICY "FedEx Admin View All Payments"
ON public.case_payments FOR SELECT
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'FEDEX_ADMIN'
);

-- DCA users can see their organization's payments
CREATE POLICY "DCA View Organization Payments"
ON public.case_payments FOR SELECT
USING (
  dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- DCA Agents can create payments
CREATE POLICY "DCA Agent Create Payments"
ON public.case_payments FOR INSERT
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('DCA_AGENT', 'DCA_MANAGER')
  AND dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- DCA Manager can update payments (for settlement batching)
CREATE POLICY "DCA Manager Update Payments"
ON public.case_payments FOR UPDATE
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'DCA_MANAGER'
  AND dca_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())
);

-- 6. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_settlement_batches_dca ON public.settlement_batches(dca_id);
CREATE INDEX IF NOT EXISTS idx_settlement_batches_status ON public.settlement_batches(status);
CREATE INDEX IF NOT EXISTS idx_case_payments_dca ON public.case_payments(dca_id);
CREATE INDEX IF NOT EXISTS idx_case_payments_settled ON public.case_payments(is_settled);
CREATE INDEX IF NOT EXISTS idx_case_payments_batch ON public.case_payments(settlement_batch_id);

-- 7. Update trigger for timestamps
CREATE TRIGGER handle_settlement_batches_updated_at 
  BEFORE UPDATE ON public.settlement_batches
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

CREATE TRIGGER handle_case_payments_updated_at 
  BEFORE UPDATE ON public.case_payments
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 8. Insert sample payment data for testing (linked to existing cases)
INSERT INTO public.case_payments (case_id, payment_amount, payment_date, payment_method, reference_number, recorded_by, dca_id, status)
SELECT 
  c.case_id,
  ROUND((c.amount_recovered * 0.3 + RANDOM() * c.amount_recovered * 0.2)::numeric, 2) as payment_amount,
  (CURRENT_DATE - (RANDOM() * 30)::int) as payment_date,
  (ARRAY['BANK_TRANSFER', 'CHEQUE', 'UPI', 'CASH', 'CARD'])[FLOOR(RANDOM() * 5 + 1)] as payment_method,
  CASE 
    WHEN RANDOM() > 0.5 THEN 'REF-' || FLOOR(RANDOM() * 1000000)::text
    ELSE 'CHQ-' || FLOOR(RANDOM() * 100000)::text
  END as reference_number,
  (SELECT id FROM public.profiles WHERE organization_id = c.dca_id AND role = 'DCA_AGENT' LIMIT 1) as recorded_by,
  c.dca_id,
  'UNSETTLED'
FROM public.cases c
WHERE c.amount_recovered > 0 
  AND c.case_status IN ('PAID', 'IN_PROGRESS')
  AND c.dca_id = 'DCA_A' -- Only for DCA_A to match our test user
LIMIT 60;

-- 9. Insert a sample settled batch for history
INSERT INTO public.settlement_batches (batch_id, dca_id, created_by, total_amount, case_count, commission_rate, commission_amount, utr_number, bank_name, status, commission_status, submitted_at)
SELECT 
  'BATCH-001',
  'DCA_A',
  (SELECT id FROM public.profiles WHERE organization_id = 'DCA_A' AND role = 'DCA_MANAGER' LIMIT 1),
  125000.00,
  15,
  0.10,
  12500.00,
  'HDFC-' || FLOOR(RANDOM() * 1000000)::text,
  'HDFC Bank',
  'VERIFIED',
  'APPROVED',
  CURRENT_TIMESTAMP - INTERVAL '15 days'
WHERE EXISTS (SELECT 1 FROM public.profiles WHERE organization_id = 'DCA_A' AND role = 'DCA_MANAGER');
